services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - docker-network
    ports:
      - 8080:80
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./app:/var/www/html/app
    depends_on:
      - postgres
    command: >
      sh -c "php artisan migrate --force &&
             apache2-foreground"
 
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      BP_DB_DATABASE: ${BP_DB_DATABASE}
    networks:
      - docker-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  botpress:
    image: botpress/server:latest
    ports:
      - '3000:3000'
    volumes:
      - botpress_data:/botpress/data
    environment:
      PG_HOST: ${DB_HOST}
      PG_PORT: ${DB_PORT}
      PG_USER: ${DB_USERNAME}
      PG_PASSWORD: ${DB_PASSWORD}
      PG_SSL: false
      PGSSLMODE: disable
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${BP_DB_DATABASE}?sslmode=disable"
    networks:
      - docker-network
    restart: always
    depends_on:
      - postgres

volumes:
  botpress_data:
  pgdata:

networks:
  docker-network:
    driver: bridge
